use std::path::{Path, PathBuf};
use colored::*;

// PythonConfig lives in crate::config — imported below
use crate::config::PythonConfig;

/// Python virtual environment in RAM session
pub struct PythonEnv {
    pub venv_dir: PathBuf,
    pub python:   String,
    pub pip:      String,
}

impl PythonEnv {
    /// Create/open venv at path using system Python (not statically linked)
    pub fn setup(version: &str, base: &Path) -> anyhow::Result<Self> {
        let venv_dir = base.to_path_buf();
        std::fs::create_dir_all(&venv_dir)?;

        // Find system Python — NOT linked statically, uses /usr/bin/python3
        let python_bin = find_system_python(version)?;

        let python = venv_dir.join("bin/python3").display().to_string();
        let pip    = venv_dir.join("bin/pip").display().to_string();

        // Create venv if not exists
        if !venv_dir.join("bin/python3").exists() {
            eprintln!("  {} Python venv ({})...", "creating".cyan(), python_bin);
            let ok = std::process::Command::new(&python_bin)
                .args(["-m", "venv", "--system-site-packages",
                       &venv_dir.display().to_string()])
                .status()
                .map(|s| s.success())
                .unwrap_or(false);
            if !ok {
                anyhow::bail!(
                    "failed to create Python venv. Is python3 installed?\n  \
                     Install: sudo apt install python3 python3-venv"
                );
            }
        }

        Ok(Self { venv_dir, python, pip })
    }

    /// Install a Python package into the venv
    /// Python libs are installed into venv (NOT statically linked)
    /// System Python runtime is used as-is
    pub fn install_package(&self, name: &str, version: Option<&str>) -> anyhow::Result<()> {
        let pkg_spec = match version {
            Some(v) => format!("{}=={}", name, v),
            None    => name.to_string(),
        };
        eprintln!("  {} {} (python)", "installing".cyan(), pkg_spec.yellow());

        let ok = std::process::Command::new(&self.pip)
            .args(["install", "--quiet", &pkg_spec])
            .status()
            .map(|s| s.success())
            .unwrap_or(false);

        if !ok {
            anyhow::bail!("pip install {} failed", pkg_spec);
        }
        eprintln!("  {} {}", "✓".green(), name.cyan());
        Ok(())
    }

    /// Generate H# FFI binding stub for a Python package
    /// The stub allows calling Python functions from H# via subprocess bridge
    pub fn generate_hsharp_binding(&self, pkg_name: &str) -> String {
        let alias = pkg_name.replace('-', "_").replace('.', "_");
        format!(r#"
;; H# Python binding for: {pkg}
;; Generated by bytes PM — calls Python via subprocess bridge
;; Runtime: system Python3 (NOT statically linked)

use "std -> process" from "proc"

pub fn {alias}_call(func: string, args: string) -> string is
    ;; Calls: python3 -c "import {pkg}; print({pkg}.<func>(<args>))"
    let cmd: string = "python3 -c \"import {pkg}; print({pkg}.\" + func + \"(\" + args + \"))\""
    return proc::shell(cmd)
end

pub fn {alias}_eval(expr: string) -> string is
    let cmd: string = "python3 -c \"import {pkg}; print(\" + expr + \")\""
    return proc::shell(cmd)
end

pub fn {alias}_import() -> bool is
    let cmd: string = "python3 -c \"import {pkg}\" && echo ok"
    let result: string = proc::shell(cmd)
    return result == "ok"
end
"#, pkg = pkg_name, alias = alias)
    }

    /// Install all packages from config
    pub fn install_all(&self, config: &PythonConfig) -> anyhow::Result<()> {
        for pkg in &config.packages {
            self.install_package(pkg, None)?;
        }
        Ok(())
    }
}

/// Setup Python deps for a bytes project
pub fn setup_python_deps(config: &PythonConfig, cache: &Path) -> anyhow::Result<()> {
    let env = PythonEnv::setup(&config.version, cache)?;
    env.install_all(config)
}

/// Resolve a python import into a generated H# binding
pub fn resolve_python_import(pkg_name: &str, version: Option<&str>) -> String {
    // Returns the H# binding stub source
    let env_stub = PythonEnv {
        venv_dir: PathBuf::new(),
        python:   "python3".into(),
        pip:      "pip3".into(),
    };
    env_stub.generate_hsharp_binding(pkg_name)
}

/// Find the system Python binary (NOT statically linked, uses system runtime)
fn find_system_python(version: &str) -> anyhow::Result<String> {
    // Prefer versioned binary
    let candidates = [
        format!("python{}", version),
        "python3".to_string(),
        "python".to_string(),
    ];

    for candidate in &candidates {
        let ok = std::process::Command::new("which")
            .arg(candidate)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if ok {
            return Ok(candidate.clone());
        }
    }
    anyhow::bail!(
        "python3 not found.\n  Install: hacker unpack python3\n  Or: sudo apt install python3 python3-venv"
    )
}
