#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# FILE: ~/.hackeros/h-sharp/hst
# AUTHOR: HackerOS Team
# DESC: H# Transpiler (HST). Transforms .hcs -> Python -> Rust Binary

import sys
import os
import gc
import re
import argparse
from lark import Lark, Transformer, v_args

# ==========================================
# 1. GRAMMAR (H#)
# ==========================================
hsharp_grammar = r"""
    %import common.CNAME -> NAME
    %import common.INT -> NUMBER
    %import common.FLOAT -> FLOAT
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS

    // Fix: Define MULTI_COMMENT before COMMENT to ensure '!!' is matched as multi-line start
    // instead of two single-line comments.
    // Regex fix: Use \n instead of \\n to match actual newlines, not literal 'n'.
    MULTI_COMMENT: "!!" /(.|\n)+?/ "!!"
    %ignore MULTI_COMMENT

    COMMENT: "!" /[^\n]*/
    %ignore COMMENT

    // Keywords definition to ensure they are captured as tokens
    KW_STATIC: "static"
    KW_DYNAMIC: "dynamic"
    KW_AUTO: "auto"
    KW_MANUAL: "manual"
    KW_AUTOMATIC: "automatic"
    KW_FAST: "fast"

    start: item*

    item: directive
        | import_stmt
        | func_def
        | object_def
        | stmt

    // --- Directives ---
    // Fix: Use named tokens so they appear in the transformer args
    directive: "===" (KW_STATIC | KW_DYNAMIC | KW_AUTO) "===" -> build_mode
             | "---" (KW_MANUAL | KW_AUTO | KW_AUTOMATIC | KW_FAST) "---" -> mem_mode

    // --- Imports ---
    import_stmt: "#" "<" SOURCE ":" NAME ">"
    SOURCE: "c" | "ruby" | "rust" | "java" | "bytes" | "virus" | "python"

    // --- Functions ---
    // 'fast' enables Numba optimization and Arena allocation
    // Fix: Use KW_FAST
    func_def: KW_FAST? "func" NAME "(" args? ")" "[" body "]"

    args: NAME ("," NAME)*

    // --- Objects ---
    object_def: "object" NAME "[" class_body "]"

    // Fix: var_decl must be its own rule to be used in class_body
    class_body: (var_decl ";")* func_def*

    body: stmt*

    // Fix: Extracted var_decl from stmt
    var_decl: "let" NAME "=" expr

    stmt: "log" (expr | STRING) ";"  -> log_stmt
        | ">" /[^\n]+/               -> sys_cmd
        | var_decl ";"               -> var_decl_stmt
        | NAME "=" expr ";"          -> assign
        | "if" expr "[" body "]" ("else" "[" body "]")? -> if_stmt
        | "while" expr "[" body "]"  -> while_stmt
        | "return" expr ";"          -> return_stmt
        | expr ";"                   -> expr_stmt

    ?expr: term
         | expr "+" term -> add
         | expr "-" term -> sub
         | expr "==" term -> eq
         | expr ">" term -> gt
         | expr "<" term -> lt

    ?term: factor
         | term "*" factor -> mul
         | term "/" factor -> div

    ?factor: NUMBER | FLOAT | NAME | STRING | "(" expr ")" | func_call

    func_call: NAME "(" call_args? ")"
    call_args: expr ("," expr)*
"""

# ==========================================
# 2. TRANSFORMER (AST -> Python)
# ==========================================
class HSTCompiler(Transformer):
    def __init__(self):
        self.user_home = os.path.expanduser("~")
        self.cache_dir = os.path.join(self.user_home, ".cache")
        self.memory_mode = "auto" # Renamed from self.mem_mode to avoid collision with method mem_mode
        self.use_arena = False
        self.imports = []
        self.preamble = []

    def start(self, items):
        # Header
        code = [
            "# GENERATED BY H# TRANSPILER (HST)",
            "import sys, os, gc, ctypes, subprocess",
            "import numpy as np",
            "import polars as pl",
            "from numba import jit",
            "",
            f"# Cache Root: {self.cache_dir}",
            ""
        ]

        # Memory Management System
        if self.memory_mode == "fast":
            self.use_arena = True
            code.append("gc.disable() # --- fast --- mode enabled")
            code.append(self._generate_arena_allocator())
        elif self.memory_mode == "manual":
            code.append("gc.disable() # --- manual --- mode enabled")
        else:
            code.append("# --- auto --- mode (Python GC)")

        code.append("")
        code.append("\n".join(self.imports))
        code.append("\n".join(self.preamble))
        code.append("\n")

        # Items are now strings (code blocks), so we can extend the list
        code.extend(items)

        # Entry Point
        if "def main():" in "\n".join(items):
            code.append("\nif __name__ == '__main__':")
            code.append("    main()")

        return "\n".join(code)

    # Fix: Handler for 'item' rule to unwrap the result from child rules (directive, stmt, etc.)
    def item(self, args):
        return args[0]

    def _generate_arena_allocator(self):
        return """
class Arena:
    _memory = []
    _idx = 0
    @staticmethod
    def alloc(val):
        Arena._memory.append(val)
        return val
    @staticmethod
    def reset():
        Arena._memory = []
"""

    # --- Directives ---
    def build_mode(self, args):
        return f"# BUILD_MODE: {args[0].value}"

    def mem_mode(self, args):
        self.memory_mode = args[0].value
        return f"# MEM_MODE: {args[0].value}"

    # --- Imports ---
    def import_stmt(self, args):
        src, name = args[0], args[1]

        if src == "python":
            return f"import {name}"

        elif src == "virus":
            path = os.path.join(self.cache_dir, "virus", name, f"{name}.so")
            return f"""
try:
    lib_{name} = ctypes.CDLL('{path}')
except Exception as e:
    print(f"VIRUS LINK ERROR: {{e}}")
    sys.exit(1)
"""
        elif src == "bytes":
            path = os.path.join(self.cache_dir, "bytes", name)
            return f"""
def {name}(*args):
    bin = '{path}'
    if not os.path.exists(bin):
        print("BYTES ERROR: Tool {name} not found")
        return
    subprocess.run([bin, *args])
"""
        return f"# IMPORT {src}:{name} (handled by build system)"

    # --- Statements ---
    def log_stmt(self, args):
        return f"print({args[0]})"

    def sys_cmd(self, args):
        cmd = args[0].value.strip()
        return f"os.system('{cmd}')"

    # Fix: Handler for explicit var_decl rule
    def var_decl(self, args):
        name, val = args[0], args[1]
        if self.use_arena:
            return f"{name} = Arena.alloc({val})"
        return f"{name} = {val}"

    # Fix: Handler for stmt that contains a var_decl
    def var_decl_stmt(self, args):
        return args[0]

    def assign(self, args):
        return f"{args[0]} = {args[1]}"

    def if_stmt(self, args):
        out = f"if {args[0]}:\n    {args[1]}"
        if len(args) > 2:
            out += f"\nelse:\n    {args[2]}"
        return out

    def while_stmt(self, args):
        return f"while {args[0]}:\n    {args[1]}"

    def return_stmt(self, args):
        return f"return {args[0]}"

    def expr_stmt(self, args):
        return str(args[0])

    # --- Functions ---
    def func_def(self, args):
        # Handle optional KW_FAST
        is_fast = False
        # Check if the first argument is the KW_FAST token
        if hasattr(args[0], 'type') and args[0].type == 'KW_FAST':
            is_fast = True
            args = args[1:] # Shift args

        name = args[0]
        # args structure now: [NAME, optional_args, body] or [NAME, body]

        if len(args) == 3:
            params = args[1]
            body = args[2]
        else:
            params = ""
            body = args[1]

        dec = "@jit(nopython=True)" if is_fast else ""
        body_indent = body.replace("\n", "\n    ") if body else "pass"

        return f"\n{dec}\ndef {name}({params}):\n    {body_indent}\n"

    def args(self, args): return ", ".join([str(a) for a in args])
    def body(self, args): return "\n".join([str(a) for a in args])

    # --- Objects ---
    def object_def(self, args):
        name = args[0]
        body = args[1].replace("\n", "\n    ")
        return f"\nclass {name}:\n    {body}\n"

    def class_body(self, args): return "\n".join([str(a) for a in args])

    # --- Expressions ---
    def add(self, a): return f"({a[0]} + {a[1]})"
    def sub(self, a): return f"({a[0]} - {a[1]})"
    def mul(self, a): return f"({a[0]} * {a[1]})"
    def div(self, a): return f"({a[0]} / {a[1]})"
    def eq(self, a): return f"({a[0]} == {a[1]})"
    def gt(self, a): return f"({a[0]} > {a[1]})"
    def lt(self, a): return f"({a[0]} < {a[1]})"
    def factor(self, a): return str(a[0])
    def func_call(self, a):
        params = a[1] if a[1] else ""
        return f"{a[0]}({params})"
    def call_args(self, a): return ", ".join([str(arg) for arg in a])


# ==========================================
# 3. MAIN ENTRY
# ==========================================
def main():
    parser_args = argparse.ArgumentParser(description="H# Transpiler")
    parser_args.add_argument("file", help="Input .hcs file")
    args = parser_args.parse_args()

    if not os.path.exists(args.file):
        print(f"Error: File {args.file} not found")
        sys.exit(1)

    with open(args.file, "r") as f:
        source = f.read()

    # Parse
    # parser='lalr' is fast and standard for context-free grammars
    parser_lark = Lark(hsharp_grammar, parser='lalr')
    try:
        tree = parser_lark.parse(source)
    except Exception as e:
        print(f"SYNTAX ERROR: {e}")
        sys.exit(1)

    # Transpile
    compiler = HSTCompiler()
    try:
        python_code = compiler.transform(tree)
        # Output to stdout
        print(python_code)
    except Exception as e:
        print(f"TRANSPILE ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
