import sys
import os
import gc
import re
import json
import argparse
from lark import Lark, Transformer, v_args, exceptions

# ==========================================
# 1. GRAMMAR (H#)
# ==========================================
hsharp_grammar = r"""
    %import common.CNAME -> NAME
    %import common.INT -> NUMBER
    %import common.FLOAT -> FLOAT
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS

    MULTI_COMMENT: "!!" /(.|\n)+?/ "!!"
    %ignore MULTI_COMMENT

    COMMENT: "!" /[^\n]*/
    %ignore COMMENT

    // Keywords
    KW_LOG: "log"
    KW_FUNC: "func"
    KW_RETURN: "return"
    KW_IF: "if"
    KW_ELSE: "else"
    KW_WHILE: "while"
    KW_LET: "let"
    KW_OBJECT: "object"

    KW_STATIC: "static"
    KW_DYNAMIC: "dynamic"
    KW_AUTO: "auto"
    KW_MANUAL: "manual"
    KW_AUTOMATIC: "automatic"
    KW_FAST: "fast"
    KW_GC: "gc"

    start: item*

    item: directive
        | import_stmt
        | func_def
        | object_def
        | stmt

    // --- Directives ---
    directive: "===" (KW_STATIC | KW_DYNAMIC | KW_AUTO) "===" -> build_mode
             | "---" (KW_MANUAL | KW_AUTO | KW_AUTOMATIC | KW_FAST | KW_GC) "---" -> mem_mode

    // --- Imports ---
    import_stmt: "#" "<" SOURCE ":" NAME ">"
    SOURCE: "c" | "ruby" | "rust" | "java" | "bytes" | "virus" | "python" | "core"

    // --- Functions ---
    func_def: KW_FAST? KW_FUNC NAME "(" args? ")" "[" body "]"

    args: NAME ("," NAME)*

    // --- Objects ---
    object_def: KW_OBJECT NAME "[" class_body "]"

    class_body: (var_decl ";"?)* func_def*

    body: stmt*

    var_decl: KW_LET NAME "=" expr

    // Helper to resolve NAME conflict between assign and expr
    lvalue: NAME

    stmt: KW_LOG expr ";"?            -> log_stmt
        | ">" /[^\n]+/               -> sys_cmd
        | var_decl ";"?               -> var_decl_stmt
        | lvalue "=" expr ";"?        -> assign
        | KW_IF expr "[" body "]" (KW_ELSE "[" body "]")? -> if_stmt
        | KW_WHILE expr "[" body "]"  -> while_stmt
        | KW_RETURN expr ";"?          -> return_stmt
        | expr ";"?                   -> expr_stmt

    ?expr: term
         | expr "+" term -> add
         | expr "-" term -> sub
         | expr "==" term -> eq
         | expr ">" term -> gt
         | expr "<" term -> lt

    ?term: factor
         | term "*" factor -> mul
         | term "/" factor -> div

    ?factor: NUMBER | FLOAT | NAME | STRING | "(" expr ")" | func_call

    func_call: NAME "(" call_args? ")"
    call_args: expr ("," expr)*
"""

# ==========================================
# 2. TRANSFORMER (AST -> Python)
# ==========================================
class HSTCompiler(Transformer):
    def __init__(self):
        # Use current working directory for cache to match Virus Build System
        # Virus creates .cache in the project root (CWD), not in user home
        self.cache_dir = os.path.join(os.getcwd(), ".cache")

        # Modes: auto (ARC), gc (Python GC), fast (Arena), manual (No GC)
        self.memory_mode = "auto"
        self.imports = []
        self.preamble = []

    def start(self, items):
        # Calculate Venv Site-Packages path to inject into the binary
        # We assume the python version running the binary is similar or compatible with the transpiler
        # This is a heuristic: .cache/venv/lib/pythonX.Y/site-packages
        py_ver = f"python{sys.version_info.major}.{sys.version_info.minor}"
        venv_site = os.path.join(self.cache_dir, "venv", "lib", py_ver, "site-packages")

        # Header
        code = [
            "# GENERATED BY H# TRANSPILER (HST)",
            "import sys, os",
            f"# INJECT VENV PATH (Configured by HST)",
            f"sys.path.append(r'{venv_site}')",
            "",
            "import gc, ctypes, subprocess",
            "try:",
            "    import numpy as np",
            "    import polars as pl",
            "    from numba import jit",
            "except ImportError as e:",
            "    print(f'[H# Runtime Warning] Missing libs: {e}. Check .cache/venv integrity.')",
            "    # Mocking for basic execution if libs fail (optional fallback)",
            "    np = None; pl = None; jit = lambda *a, **k: (lambda f: f)",
            "",
            f"# Cache Root: {self.cache_dir}",
            ""
        ]

        # Memory Management System
        if self.memory_mode == "fast":
            code.append("gc.disable() # --- fast --- mode (Arena)")
            code.append(self._generate_arena_allocator())
        elif self.memory_mode in ["auto", "automatic"]:
            code.append("gc.disable() # --- auto --- mode (Custom ARC)")
            code.append(self._generate_arc_system())
        elif self.memory_mode == "manual":
            code.append("gc.disable() # --- manual --- mode (Unsafe)")
        elif self.memory_mode == "gc":
            code.append("gc.enable() # --- gc --- mode (Python Native)")
        else:
            code.append("gc.disable() # Defaulting to ARC")
            code.append(self._generate_arc_system())

        code.append("")
        code.append("\n".join(self.imports))
        code.append("\n".join(self.preamble))
        code.append("\n")

        code.extend(items)

        # Entry Point
        if "def main():" in "\n".join(items):
            code.append("\nif __name__ == '__main__':")
            code.append("    main()")

        return "\n".join(code)

    def item(self, args):
        return args[0]

    def _generate_arena_allocator(self):
        return """
class Arena:
    _memory = []
    @staticmethod
    def alloc(val):
        Arena._memory.append(val)
        return val
"""

    def _generate_arc_system(self):
        return """
# H# Custom ARC (Automatic Reference Counting)
class Arc:
    def __init__(self, val):
        # Flatten nested Arcs to prevent infinite wrapping
        while hasattr(val, 'val'):
            val = val.val
        self.val = val
        self.rc = 1

    def retain(self):
        self.rc += 1
        return self

    def release(self):
        self.rc -= 1
        if self.rc <= 0:
            self.free()

    def free(self):
        self.val = None

    # Truthiness (Crucial for loops!)
    def __bool__(self):
        return bool(self.val)

    def __nonzero__(self):
        return bool(self.val)

    def __repr__(self): return str(self.val)
    def __str__(self): return str(self.val)

    # Helpers for mixing Arc with raw types
    def _get(self, other):
        # Recursively unwrap if needed (though init handles most)
        if hasattr(other, 'val'): return other.val
        return other

    # Arithmetic
    def __add__(self, o): return Arc(self.val + self._get(o))
    def __sub__(self, o): return Arc(self.val - self._get(o))
    def __mul__(self, o): return Arc(self.val * self._get(o))
    def __truediv__(self, o): return Arc(self.val / self._get(o))

    # Reverse Arithmetic (for Int + Arc)
    def __radd__(self, o): return Arc(self._get(o) + self.val)
    def __rsub__(self, o): return Arc(self._get(o) - self.val)
    def __rmul__(self, o): return Arc(self._get(o) * self.val)
    def __rtruediv__(self, o): return Arc(self._get(o) / self.val)

    # Comparison
    def __eq__(self, o): return self.val == self._get(o)
    def __gt__(self, o): return self.val > self._get(o)
    def __lt__(self, o): return self.val < self._get(o)
    def __ge__(self, o): return self.val >= self._get(o)
    def __le__(self, o): return self.val <= self._get(o)
    def __ne__(self, o): return self.val != self._get(o)
"""

    # --- Directives ---
    def build_mode(self, args):
        return f"# BUILD_MODE: {args[0].value}"

    def mem_mode(self, args):
        self.memory_mode = args[0].value
        return f"# MEM_MODE: {args[0].value}"

    # --- Imports ---
    def import_stmt(self, args):
        src, name = args[0], args[1]

        if src == "python":
            return f"import {name}"

        elif src == "virus":
            path = os.path.join(self.cache_dir, "virus", name, f"{name}.so")
            return f"try:\n    lib_{name} = ctypes.CDLL('{path}')\nexcept: pass"

        elif src == "bytes":
            path = os.path.join(self.cache_dir, "bytes", name)
            return f"def {name}(*a):\n    subprocess.run(['{path}', *a])"

        elif src == "rust":
            # Just a marker for Virus Build System to inject into Cargo.toml
            return f"# H#_RUST_DEP: {name}"

        elif src == "core":
            # Core libraries are compiled H# files located in /usr/lib/h-sharp/core
            # Virus compiles them to .so and places them in cache/core
            path = os.path.join(self.cache_dir, "core", f"lib{name}.so")
            return f"try:\n    core_{name} = ctypes.CDLL('{path}')\nexcept Exception as e: print(f'Core Load Error: {{e}}')"

        return f"# IMPORT {src}:{name}"

    # --- Statements ---
    def log_stmt(self, args):
        # args[0] is KW_LOG (token), args[1] is the expr
        return f"print({args[1]})"

    def sys_cmd(self, args):
        # args[0] is the regex match for /[^\n]+/
        cmd = args[0].value.strip()
        return f"os.system('{cmd}')"

    def var_decl(self, args):
        # args[0] is KW_LET, args[1] is NAME, args[2] is expr
        name = args[1]
        val = args[2]
        # In Auto/ARC mode, wrap values
        if self.memory_mode in ["auto", "automatic"]:
            return f"{name} = Arc({val})"
        elif self.memory_mode == "fast":
            return f"{name} = Arena.alloc({val})"
        return f"{name} = {val}"

    def var_decl_stmt(self, args): return args[0]

    def lvalue(self, args): return args[0]
    def assign(self, args): return f"{args[0]} = {args[1]}"

    def if_stmt(self, args):
        # args[0] = KW_IF
        # args[1] = expr (condition)
        # args[2] = body (true block)
        # Optional: args[3] = KW_ELSE, args[4] = body (false block)
        body_true = str(args[2]).replace("\n", "\n    ")
        out = f"if {args[1]}:\n    {body_true}"
        if len(args) > 3:
            body_false = str(args[4]).replace("\n", "\n    ")
            out += f"\nelse:\n    {body_false}"
        return out

    def while_stmt(self, args):
        # args[0] = KW_WHILE, args[1] = expr, args[2] = body
        body = str(args[2]).replace("\n", "\n    ")
        return f"while {args[1]}:\n    {body}"

    def return_stmt(self, args):
        # args[0] = KW_RETURN, args[1] = expr
        return f"return {args[1]}"

    def expr_stmt(self, args): return str(args[0])

    # --- Functions ---
    def func_def(self, args):
        has_fast = False
        name_idx = -1

        # Scan for NAME token to locate function name.
        # Everything before it is qualifiers (KW_FUNC, KW_FAST).
        # Everything after it is children (args and body).
        for i, arg in enumerate(args):
            if hasattr(arg, 'type'):
                if arg.type == 'KW_FAST':
                    has_fast = True
                elif arg.type == 'NAME':
                    name_idx = i
                    break

        if name_idx == -1: return "" # Should be caught by parser syntax error

        name = args[name_idx].value
        children = args[name_idx+1:]

        params_str = ""
        body = ""

        if len(children) == 2:
            params_str = str(children[0])
            body = str(children[1])
        elif len(children) == 1:
            body = str(children[0])

        if has_fast:
             # 1. Regex strip Arc() wrapping from var declarations in body
            jit_body = re.sub(r'\bArc\s*\((.*?)\)', r'\1', body)
            jit_body_indent = jit_body.replace("\n", "\n    ") if jit_body else "pass"
            jit_name = f"_jit_{name}"
            jit_func = f"@jit(nopython=True)\ndef {jit_name}({params_str}):\n    {jit_body_indent}\n"

            arg_names = [x.strip() for x in params_str.split(',') if x.strip()]
            unwrap_code = ""
            call_args = []
            for arg in arg_names:
                unwrap_code += f"    _{arg} = {arg}.val if hasattr({arg}, 'val') else {arg}\n"
                call_args.append(f"_{arg}")

            call_args_str = ", ".join(call_args)
            wrapper = f"""
def {name}({params_str}):
{unwrap_code}
    res = {jit_name}({call_args_str})
    return Arc(res)
"""
            return f"\n{jit_func}\n{wrapper}\n"

        # Normal Function
        body_indent = body.replace("\n", "\n    ") if body else "pass"
        return f"\ndef {name}({params_str}):\n    {body_indent}\n"

    def args(self, args):
        # Ensure we use .value for tokens to avoid getting "Token(NAME, 'val')"
        return ", ".join([str(a.value) if hasattr(a, 'value') else str(a) for a in args])

    def body(self, args): return "\n".join([str(a) for a in args])

    # --- Objects ---
    def object_def(self, args):
        # args[0] = KW_OBJECT
        # args[1] = NAME
        # args[2] = body
        name = args[1]
        body = args[2].replace("\n", "\n    ")
        return f"\nclass {name}:\n    {body}\n"

    def class_body(self, args): return "\n".join([str(a) for a in args])

    # --- Expressions ---
    def add(self, a): return f"({a[0]} + {a[1]})"
    def sub(self, a): return f"({a[0]} - {a[1]})"
    def mul(self, a): return f"({a[0]} * {a[1]})"
    def div(self, a): return f"({a[0]} / {a[1]})"
    def eq(self, a): return f"({a[0]} == {a[1]})"
    def gt(self, a): return f"({a[0]} > {a[1]})"
    def lt(self, a): return f"({a[0]} < {a[1]})"
    def factor(self, a): return str(a[0])

    def func_call(self, a):
        name = a[0]
        params = a[1] if len(a) > 1 else ""
        return f"{name}({params})"

    def call_args(self, a): return ", ".join([str(arg) for arg in a])


# ==========================================
# 3. MAIN ENTRY
# ==========================================
def main():
    parser_args = argparse.ArgumentParser(description="H# Transpiler")
    parser_args.add_argument("file", help="Input .hcs file")
    args = parser_args.parse_args()

    if not os.path.exists(args.file):
        print(f"Error: File {args.file} not found")
        sys.exit(1)

    with open(args.file, "r") as f:
        source = f.read()

    parser_lark = Lark(hsharp_grammar, parser='lalr')
    try:
        tree = parser_lark.parse(source)
        compiler = HSTCompiler()
        python_code = compiler.transform(tree)
        print(python_code)
    except exceptions.UnexpectedToken as e:
        # Structured Error Output for Virus Build System (Go)
        err = {
            "type": "SyntaxError",
            "msg": f"Unexpected token: '{e.token}'",
            "line": e.line,
            "col": e.column,
            "expected": sorted(list(e.expected)) if e.expected else []
        }
        # Print magic string for Go to capture
        print(f"__HST_JSON_ERR__{json.dumps(err)}")
        sys.exit(1)
    except exceptions.UnexpectedCharacters as e:
        err = {
            "type": "LexerError",
            "msg": f"Unexpected character: '{e.char}'",
            "line": e.line,
            "col": e.column
        }
        print(f"__HST_JSON_ERR__{json.dumps(err)}")
        sys.exit(1)
    except Exception as e:
        # Fallback for other errors
        print(f"HST ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
