#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# FILE: ~/.hackeros/h-sharp/hst
# AUTHOR: HackerOS Core Team
# DESC: H# Transpiler (HST). Transforms .hcs -> Python -> Rust Binary

import sys
import os
import gc
import re
import argparse
from lark import Lark, Transformer, v_args

# ==========================================
# 1. GRAMMAR (H#)
# ==========================================
hsharp_grammar = r"""
    %import common.CNAME -> NAME
    %import common.INT -> NUMBER
    %import common.FLOAT -> FLOAT
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS

    MULTI_COMMENT: "!!" /(.|\n)+?/ "!!"
    %ignore MULTI_COMMENT

    COMMENT: "!" /[^\n]*/
    %ignore COMMENT

    // Keywords
    KW_STATIC: "static"
    KW_DYNAMIC: "dynamic"
    KW_AUTO: "auto"
    KW_MANUAL: "manual"
    KW_AUTOMATIC: "automatic"
    KW_FAST: "fast"
    KW_GC: "gc"

    start: item*

    item: directive
        | import_stmt
        | func_def
        | object_def
        | stmt

    // --- Directives ---
    directive: "===" (KW_STATIC | KW_DYNAMIC | KW_AUTO) "===" -> build_mode
             | "---" (KW_MANUAL | KW_AUTO | KW_AUTOMATIC | KW_FAST | KW_GC) "---" -> mem_mode

    // --- Imports ---
    import_stmt: "#" "<" SOURCE ":" NAME ">"
    SOURCE: "c" | "ruby" | "rust" | "java" | "bytes" | "virus" | "python"

    // --- Functions ---
    func_def: KW_FAST? "func" NAME "(" args? ")" "[" body "]"

    args: NAME ("," NAME)*

    // --- Objects ---
    object_def: "object" NAME "[" class_body "]"

    class_body: (var_decl ";")* func_def*

    body: stmt*

    var_decl: "let" NAME "=" expr

    stmt: "log" (expr | STRING) ";"  -> log_stmt
        | ">" /[^\n]+/               -> sys_cmd
        | var_decl ";"               -> var_decl_stmt
        | NAME "=" expr ";"          -> assign
        | "if" expr "[" body "]" ("else" "[" body "]")? -> if_stmt
        | "while" expr "[" body "]"  -> while_stmt
        | "return" expr ";"          -> return_stmt
        | expr ";"                   -> expr_stmt

    ?expr: term
         | expr "+" term -> add
         | expr "-" term -> sub
         | expr "==" term -> eq
         | expr ">" term -> gt
         | expr "<" term -> lt

    ?term: factor
         | term "*" factor -> mul
         | term "/" factor -> div

    ?factor: NUMBER | FLOAT | NAME | STRING | "(" expr ")" | func_call

    func_call: NAME "(" call_args? ")"
    call_args: expr ("," expr)*
"""

# ==========================================
# 2. TRANSFORMER (AST -> Python)
# ==========================================
class HSTCompiler(Transformer):
    def __init__(self):
        self.user_home = os.path.expanduser("~")
        self.cache_dir = os.path.join(self.user_home, ".cache")
        # Modes: auto (ARC), gc (Python GC), fast (Arena), manual (No GC)
        self.memory_mode = "auto"
        self.imports = []
        self.preamble = []

    def start(self, items):
        # Calculate Venv Site-Packages path to inject into the binary
        # We assume the python version running the binary is similar or compatible with the transpiler
        # This is a heuristic: .cache/venv/lib/pythonX.Y/site-packages
        py_ver = f"python{sys.version_info.major}.{sys.version_info.minor}"
        venv_site = os.path.join(self.cache_dir, "venv", "lib", py_ver, "site-packages")

        # Header
        code = [
            "# GENERATED BY H# TRANSPILER (HST)",
            "import sys, os",
            f"# INJECT VENV PATH (Configured by HST)",
            f"sys.path.append(r'{venv_site}')",
            "",
            "import gc, ctypes, subprocess",
            "import numpy as np",
            "import polars as pl",
            "from numba import jit",
            "",
            f"# Cache Root: {self.cache_dir}",
            ""
        ]

        # Memory Management System
        if self.memory_mode == "fast":
            code.append("gc.disable() # --- fast --- mode (Arena)")
            code.append(self._generate_arena_allocator())
        elif self.memory_mode in ["auto", "automatic"]:
            code.append("gc.disable() # --- auto --- mode (Custom ARC)")
            code.append(self._generate_arc_system())
        elif self.memory_mode == "manual":
            code.append("gc.disable() # --- manual --- mode (Unsafe)")
        elif self.memory_mode == "gc":
            code.append("gc.enable() # --- gc --- mode (Python Native)")
        else:
            code.append("gc.disable() # Defaulting to ARC")
            code.append(self._generate_arc_system())

        code.append("")
        code.append("\n".join(self.imports))
        code.append("\n".join(self.preamble))
        code.append("\n")

        code.extend(items)

        # Entry Point
        if "def main():" in "\n".join(items):
            code.append("\nif __name__ == '__main__':")
            code.append("    main()")

        return "\n".join(code)

    def item(self, args):
        return args[0]

    def _generate_arena_allocator(self):
        return """
class Arena:
    _memory = []
    @staticmethod
    def alloc(val):
        Arena._memory.append(val)
        return val
"""

    def _generate_arc_system(self):
        return """
# H# Custom ARC (Automatic Reference Counting)
class Arc:
    def __init__(self, val):
        self.val = val
        self.rc = 1

    def retain(self):
        self.rc += 1
        return self

    def release(self):
        self.rc -= 1
        if self.rc <= 0:
            self.free()

    def free(self):
        self.val = None

    def __repr__(self): return str(self.val)
    def __str__(self): return str(self.val)

    # Helpers for mixing Arc with raw types
    def _get(self, other):
        return other.val if hasattr(other, 'val') else other

    # Arithmetic
    def __add__(self, o): return Arc(self.val + self._get(o))
    def __sub__(self, o): return Arc(self.val - self._get(o))
    def __mul__(self, o): return Arc(self.val * self._get(o))
    def __truediv__(self, o): return Arc(self.val / self._get(o))

    # Comparison
    def __eq__(self, o): return self.val == self._get(o)
    def __gt__(self, o): return self.val > self._get(o)
    def __lt__(self, o): return self.val < self._get(o)
"""

    # --- Directives ---
    def build_mode(self, args):
        return f"# BUILD_MODE: {args[0].value}"

    def mem_mode(self, args):
        self.memory_mode = args[0].value
        return f"# MEM_MODE: {args[0].value}"

    # --- Imports ---
    def import_stmt(self, args):
        src, name = args[0], args[1]
        if src == "python":
            return f"import {name}"
        elif src == "virus":
            path = os.path.join(self.cache_dir, "virus", name, f"{name}.so")
            return f"try:\n    lib_{name} = ctypes.CDLL('{path}')\nexcept: pass"
        elif src == "bytes":
            path = os.path.join(self.cache_dir, "bytes", name)
            return f"def {name}(*a):\n    subprocess.run(['{path}', *a])"
        return f"# IMPORT {src}:{name}"

    # --- Statements ---
    def log_stmt(self, args):
        return f"print({args[0]})"

    def sys_cmd(self, args):
        cmd = args[0].value.strip()
        return f"os.system('{cmd}')"

    def var_decl(self, args):
        name, val = args[0], args[1]
        # In Auto/ARC mode, wrap values
        if self.memory_mode in ["auto", "automatic"]:
            return f"{name} = Arc({val})"
        elif self.memory_mode == "fast":
            return f"{name} = Arena.alloc({val})"
        return f"{name} = {val}"

    def var_decl_stmt(self, args): return args[0]
    def assign(self, args): return f"{args[0]} = {args[1]}"

    def if_stmt(self, args):
        out = f"if {args[0]}:\n    {args[1]}"
        if len(args) > 2: out += f"\nelse:\n    {args[2]}"
        return out

    def while_stmt(self, args):
        return f"while {args[0]}:\n    {args[1]}"

    def return_stmt(self, args): return f"return {args[0]}"
    def expr_stmt(self, args): return str(args[0])

    # --- Functions ---
    def func_def(self, args):
        is_fast = False
        if hasattr(args[0], 'type') and args[0].type == 'KW_FAST':
            is_fast = True
            args = args[1:]

        name = args[0]
        params_str = str(args[1]) if len(args) == 3 else ""
        body = str(args[2]) if len(args) == 3 else str(args[1])

        # HACK: If fast/JIT, we must STRIP Arc() usage from the body and unwrap arguments
        # Numba nopython mode cannot handle Arc classes.
        if is_fast:
            # 1. Regex strip Arc() wrapping from var declarations in body
            # Matches "Arc(...)" and replaces with "..."
            # Note: This is a simple heuristic. Nested Arcs might be tricky.
            jit_body = re.sub(r'\bArc\s*\((.*?)\)', r'\1', body)
            jit_body_indent = jit_body.replace("\n", "\n    ") if jit_body else "pass"

            jit_name = f"_jit_{name}"

            # 2. Generate JIT Function
            jit_func = f"@jit(nopython=True)\ndef {jit_name}({params_str}):\n    {jit_body_indent}\n"

            # 3. Generate Wrapper Trampoline to unwrap Arc args
            # We need to know arg names to unwrap them
            arg_names = [x.strip() for x in params_str.split(',') if x.strip()]
            unwrap_code = ""
            call_args = []

            for arg in arg_names:
                unwrap_code += f"    _{arg} = {arg}.val if hasattr({arg}, 'val') else {arg}\n"
                call_args.append(f"_{arg}")

            call_args_str = ", ".join(call_args)

            wrapper = f"""
def {name}({params_str}):
{unwrap_code}
    res = {jit_name}({call_args_str})
    return Arc(res)
"""
            return f"\n{jit_func}\n{wrapper}\n"

        # Normal Function
        body_indent = body.replace("\n", "\n    ") if body else "pass"
        return f"\ndef {name}({params_str}):\n    {body_indent}\n"

    def args(self, args): return ", ".join([str(a) for a in args])
    def body(self, args): return "\n".join([str(a) for a in args])

    # --- Objects ---
    def object_def(self, args):
        name = args[0]
        body = args[1].replace("\n", "\n    ")
        return f"\nclass {name}:\n    {body}\n"

    def class_body(self, args): return "\n".join([str(a) for a in args])

    # --- Expressions ---
    def add(self, a): return f"({a[0]} + {a[1]})"
    def sub(self, a): return f"({a[0]} - {a[1]})"
    def mul(self, a): return f"({a[0]} * {a[1]})"
    def div(self, a): return f"({a[0]} / {a[1]})"
    def eq(self, a): return f"({a[0]} == {a[1]})"
    def gt(self, a): return f"({a[0]} > {a[1]})"
    def lt(self, a): return f"({a[0]} < {a[1]})"
    def factor(self, a): return str(a[0])

    def func_call(self, a):
        params = a[1] if a[1] else ""
        return f"{a[0]}({params})"
    def call_args(self, a): return ", ".join([str(arg) for arg in a])


# ==========================================
# 3. MAIN ENTRY
# ==========================================
def main():
    parser_args = argparse.ArgumentParser(description="H# Transpiler")
    parser_args.add_argument("file", help="Input .hcs file")
    args = parser_args.parse_args()

    if not os.path.exists(args.file):
        print(f"Error: File {args.file} not found")
        sys.exit(1)

    with open(args.file, "r") as f:
        source = f.read()

    parser_lark = Lark(hsharp_grammar, parser='lalr')
    try:
        tree = parser_lark.parse(source)
        compiler = HSTCompiler()
        python_code = compiler.transform(tree)
        print(python_code)
    except Exception as e:
        print(f"HST ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
