use crate::typechecker::HType;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    /// `hsharp preview` / REPL — tree-walking interpreter crate.
    Interpreter,
    /// `h#` — the LLVM-backed AOT compiler (this crate).
    Llvm,
}

impl Backend {
    pub const ALL: [Backend; 2] = [Backend::Interpreter, Backend::Llvm];

    pub fn name(&self) -> &'static str {
        match self {
            Backend::Interpreter => "interpreter (hsharp preview)",
            Backend::Llvm        => "h# (LLVM, --release)",
        }
    }
}

/// One builtin function's shape + which backends implement it.
pub struct BuiltinSpec {
    /// The name(s) users call (aliases, e.g. "trim"/"str_trim").
    pub names:   &'static [&'static str],
    /// Parameter types (for typechecking; arity overloads like `exec`
    /// list their MAX arity here and the typechecker stays permissive
    /// about fewer args — see typechecker.rs comment on `exec`).
    pub params:  fn() -> Vec<HType>,
    pub ret:     fn() -> HType,
    /// The `hsh_*` C symbol used by the H# runtime (`runtime.rs`,
    /// `builtins.rs::LlvmBuiltins`). `None` for builtins implemented purely
    /// as AST rewrites (e.g. derive dispatch — see optimize_ast.rs) with no
    /// runtime counterpart.
    pub c_symbol: Option<&'static str>,
    /// Backends that currently have a working implementation. Used by
    /// `features.rs` to produce "not supported by backend X" errors.
    pub backends: &'static [Backend],
    /// Short human description, used in `bytes doc`/`--list-builtins`.
    pub doc: &'static str,
}

/// The canonical builtin table.
pub static BUILTINS: &[BuiltinSpec] = &[
    BuiltinSpec {
        names: &["shell", "cmd"],
        params: || vec![HType::Str],
        ret: || HType::Str,
        c_symbol: Some("hsh_shell"),
        backends: &[Backend::Interpreter, Backend::Llvm],
        doc: "Run a command through /bin/sh and capture stdout+stderr. \
SECURITY: prefer shell_escape()/exec() for untrusted input.",
    },
BuiltinSpec {
    names: &["shell_escape", "shquote"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_shell_escape"),
    // Implemented on Llvm (runtime.rs + builtins.rs, this session).
    // Interpreter dispatch still needs a matching arm (not in this
    // crate — see interpreter/src/lib.rs).
    backends: &[Backend::Llvm],
    doc: "POSIX single-quote-escape a string for safe embedding into shell().",
},
BuiltinSpec {
    names: &["exec"],
    params: || vec![HType::Str, HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_exec1"), // codegen picks exec1..4 by call arity
    backends: &[Backend::Llvm],
    doc: "Direct fork+execve (no shell). exec(cmd[, a1[, a2[, a3]]]) -> captured stdout+stderr.",
},
BuiltinSpec {
    names: &["py_eval"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_py_eval"),
    backends: &[Backend::Llvm],
    doc: "extern [python, ...] phase 1 bridge: execvp(\"python3\", [\"-c\", code]) -> stdout.",
},
BuiltinSpec {
    names: &["regex_match"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: Some("hsh_regex_match"),
    backends: &[Backend::Llvm],
    doc: "PCRE2 regex match (§11) — full lookahead/lookbehind/non-greedy support.",
},
BuiltinSpec {
    names: &["regex_find"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_regex_find"),
    backends: &[Backend::Llvm],
    doc: "PCRE2 regex find — returns first match or empty string.",
},
BuiltinSpec {
    names: &["regex_replace"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_regex_replace"),
    backends: &[Backend::Llvm],
    doc: "PCRE2 regex replace (global, supports $1/$2 capture group refs).",
},
BuiltinSpec {
    names: &["db_query_bind"],
    params: || vec![HType::Str, HType::Str, HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_sqlite_query_bind1"), // codegen picks bind1/2/3 by arity
    backends: &[Backend::Llvm],
    doc: "Parameterized SQLite query (§12) — SQL-injection-safe via sqlite3_bind_text. \
db_query_bind(db, \"SELECT * FROM t WHERE id=?\", id)",
},
BuiltinSpec {
    names: &["run_cmd_exec"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Int,
    c_symbol: Some("hsh_run_cmd_exec"),
    backends: &[Backend::Llvm],
    doc: "Internal: runs `cmd` via /bin/sh with a timeout (seconds; <=0 = none), \
returns the real exit code (-1 = couldn't start, -2 = timed out). Stdout/stderr are read \
back separately via run_cmd_last_stdout()/run_cmd_last_stderr() — see proc::run_cmd's \
H#-level wrapper in stdlib_shims.rs, which is what user code should actually call.",
},
BuiltinSpec {
    names: &["run_cmd_last_stdout"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_run_cmd_last_stdout"),
    backends: &[Backend::Llvm],
    doc: "Internal: stdout captured by the most recent run_cmd_exec() call.",
},
BuiltinSpec {
    names: &["run_cmd_last_stderr"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_run_cmd_last_stderr"),
    backends: &[Backend::Llvm],
    doc: "Internal: stderr captured by the most recent run_cmd_exec() call.",
},
BuiltinSpec {
    names: &["str_split_count"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_str_split_count"),
    backends: &[Backend::Llvm],
    doc: "Internal: how many parts `s` splits into on `sep`. See str_split's \
H#-level wrapper in stdlib_shims.rs, which is what user code should actually call.",
},
BuiltinSpec {
    names: &["str_split_part"],
    params: || vec![HType::Str, HType::Str, HType::Int],
    ret: || HType::Str,
    c_symbol: Some("hsh_str_split_part"),
    backends: &[Backend::Llvm],
    doc: "Internal: the i-th (0-indexed) part of `s` split on `sep`.",
},
BuiltinSpec {
    names: &["int_to_str"],
    params: || vec![HType::Int],
    ret: || HType::Str,
    c_symbol: Some("hsh_int_to_str"),
    backends: &[Backend::Llvm],
    doc: "conv::int_to_str — integer to its base-10 string representation.",
},
BuiltinSpec {
    names: &["str_to_int"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_str_to_int"),
    backends: &[Backend::Llvm],
    doc: "conv::str_to_int — parses a base-10 integer prefix; 0 if none found (never crashes on bad input).",
},
BuiltinSpec {
    names: &["env_get"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_env_get"),
    backends: &[Backend::Llvm],
    doc: "env::get — environment variable value, or \"\" if unset.",
},
BuiltinSpec {
    names: &["env_read_line"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_env_read_line"),
    backends: &[Backend::Llvm],
    doc: "env::read_line — one line from stdin, trailing newline stripped; \"\" on EOF.",
},
BuiltinSpec {
    names: &["fs_remove"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_remove_file"),
    backends: &[Backend::Llvm],
    doc: "fs::remove — delete a single file.",
},
BuiltinSpec {
    names: &["fs_remove_dir"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_remove_dir_recursive"),
    backends: &[Backend::Llvm],
    doc: "fs::remove_dir — recursively delete a directory tree (shells out to `rm -rf`, see runtime/core.c's doc comment).",
},
BuiltinSpec {
    names: &["fs_rename"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_rename"),
    backends: &[Backend::Llvm],
    doc: "fs::rename — move/rename a file or directory.",
},
BuiltinSpec {
    names: &["fs_chdir"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_chdir"),
    backends: &[Backend::Llvm],
    doc: "fs::chdir — change the process's current working directory; returns 1 on \
          success, 0 on failure. Previously aliased to `fs_cwd` as a no-op placeholder \
          (see interpreter/src/helpers.rs) — now a real implementation on both backends.",
},
BuiltinSpec {
    names: &["json_set_str"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_json_set_str"),
    backends: &[Backend::Llvm],
    doc: "json::set_str — insert-or-replace a string field in a flat JSON object, returns the updated JSON text.",
},
BuiltinSpec {
    names: &["json_get_str"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_json_get"),
    backends: &[Backend::Llvm],
    doc: "json::get_str — read a string field from a flat JSON object; \"\" if absent.",
},
BuiltinSpec {
    names: &["sin", "cos", "tan", "sqrt", "floor", "ceil"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None, // dispatched by name in codegen.rs, not a 1:1 c_symbol
    backends: &[Backend::Llvm],
    doc: "math:: — thin libm wrappers.",
},
BuiltinSpec {
    names: &["pow"],
    params: || vec![HType::F64, HType::F64],
    ret: || HType::F64,
    c_symbol: Some("hsh_pow"),
    backends: &[Backend::Llvm],
    doc: "math::pow(base, exponent).",
},
BuiltinSpec {
    names: &["abs"],
    params: || vec![HType::Int],
    ret: || HType::Int,
    c_symbol: None, // dispatches to hsh_abs_i or hsh_abs_f by argument type
    backends: &[Backend::Llvm],
    doc: "math::abs — works on both int and float arguments.",
},
BuiltinSpec {
    names: &["min", "max"],
    params: || vec![HType::Int, HType::Int],
    ret: || HType::Int,
    c_symbol: None, // dispatches by argument type, same as abs
    backends: &[Backend::Llvm],
    doc: "math::min / math::max — work on both int and float arguments.",
},
BuiltinSpec {
    names: &["hostname"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_hostname"),
    backends: &[Backend::Llvm],
    doc: "os::hostname.",
},
BuiltinSpec {
    names: &["username"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_username"),
    backends: &[Backend::Llvm],
    doc: "os::username — $USER/$LOGNAME, falls back to the passwd database.",
},
BuiltinSpec {
    names: &["platform"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_platform"),
    backends: &[Backend::Llvm],
    doc: "os::platform — \"linux\" / \"macos\" / \"windows\".",
},
BuiltinSpec {
    names: &["getcwd", "cwd"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: Some("hsh_getcwd"),
    backends: &[Backend::Llvm],
    doc: "env::cwd — current working directory.",
},
BuiltinSpec {
    names: &["env_set"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: Some("hsh_setenv"),
    backends: &[Backend::Llvm],
    doc: "env::set — sets an environment variable for this process.",
},
BuiltinSpec {
    names: &["now_unix"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: Some("hsh_now_unix"),
    backends: &[Backend::Llvm],
    doc: "time::now_unix — seconds since the Unix epoch.",
},
BuiltinSpec {
    names: &["now_ms"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: Some("hsh_now_ms"),
    backends: &[Backend::Llvm],
    doc: "time — milliseconds since the Unix epoch.",
},
BuiltinSpec {
    names: &["sleep_ms"],
    params: || vec![HType::Int],
    ret: || HType::Int,
    c_symbol: Some("hsh_sleep_ms"),
    backends: &[Backend::Llvm],
    doc: "time::sleep_ms — blocks the current thread for the given duration.",
},
BuiltinSpec {
    names: &["base64_encode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_base64_encode"),
    backends: &[Backend::Llvm],
    doc: "encoding::base64 encode (standard alphabet, '=' padded).",
},
BuiltinSpec {
    names: &["base64_decode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_base64_decode"),
    backends: &[Backend::Llvm],
    doc: "encoding::base64 decode.",
},
BuiltinSpec {
    names: &["url_encode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_url_encode"),
    backends: &[Backend::Llvm],
    doc: "encoding::url percent-encode (RFC 3986 unreserved chars left as-is).",
},
BuiltinSpec {
    names: &["url_decode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: Some("hsh_url_decode"),
    backends: &[Backend::Llvm],
    doc: "encoding::url percent-decode (also accepts '+' as space).",
},
BuiltinSpec {
    names: &["map_new"],
    params: || vec![HType::Int],
    ret: || HType::Any,
    c_symbol: Some("hsh_map_new"),
    backends: &[Backend::Llvm],
    doc: "HashMap constructor. map_new(true) for string keys (content hash/eq), \
map_new(false) for int keys. See runtime/core.c's HshMap doc comment.",
},
BuiltinSpec {
    names: &["map_set"],
    params: || vec![HType::Any, HType::Any, HType::Any],
    ret: || HType::Void,
    c_symbol: Some("hsh_map_set"),
    backends: &[Backend::Llvm],
    doc: "map_set(map, key, value) — insert or overwrite.",
},
BuiltinSpec {
    names: &["map_get", "map_get_int"],
    params: || vec![HType::Any, HType::Any],
    ret: || HType::Int,
    c_symbol: Some("hsh_map_get"),
    backends: &[Backend::Llvm],
    doc: "map_get(map, key) — 0 if absent; use map_has to distinguish absence from a stored 0.",
},
BuiltinSpec {
    names: &["map_get_str"],
    params: || vec![HType::Any, HType::Any],
    ret: || HType::Str,
    c_symbol: Some("hsh_map_get"),
    backends: &[Backend::Llvm],
    doc: "map_get_str(map, key) — same lookup as map_get, return reinterpreted as a string.",
},
BuiltinSpec {
    names: &["map_has"],
    params: || vec![HType::Any, HType::Any],
    ret: || HType::Bool,
    c_symbol: Some("hsh_map_has"),
    backends: &[Backend::Llvm],
    doc: "map_has(map, key) — real presence check (distinguishes absent from stored-0/false).",
},
BuiltinSpec {
    names: &["map_remove"],
    params: || vec![HType::Any, HType::Any],
    ret: || HType::Bool,
    c_symbol: Some("hsh_map_remove"),
    backends: &[Backend::Llvm],
    doc: "map_remove(map, key) — true if a key was actually removed.",
},
BuiltinSpec {
    names: &["map_len"],
    params: || vec![HType::Any],
    ret: || HType::Int,
    c_symbol: Some("hsh_map_len"),
    backends: &[Backend::Llvm],
    doc: "map_len(map) — number of live entries.",
},
BuiltinSpec {
    names: &["map_keys"],
    params: || vec![HType::Any],
    ret: || HType::Array(Box::new(HType::Any)),
    c_symbol: Some("hsh_map_keys"),
    backends: &[Backend::Llvm],
    doc: "map_keys(map) — array of keys, unspecified order (bucket order).",
},
BuiltinSpec {
    names: &["map_clear"],
    params: || vec![HType::Any],
    ret: || HType::Void,
    c_symbol: Some("hsh_map_clear"),
    backends: &[Backend::Llvm],
    doc: "map_clear(map) — removes all entries, keeps the table allocated.",
},
BuiltinSpec {
    names: &["await"],
    params: || vec![HType::Any],
    ret: || HType::Any,
    c_symbol: None,
    // Interpreter-only — `h#` (LLVM) has no async runtime. A call site
    // using `await` when compiling with `h#` should error via
    // features.rs rather than silently treating it as a synchronous
    // no-op.
    backends: &[Backend::Interpreter],
    doc: "Await an async expression. Interpreter only until h# gains an async runtime.",
},
BuiltinSpec {
    names: &["__builtin_crypto_random_bytes"],
    params: || vec![HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Real cryptographically-random bytes (/dev/urandom). Interpreter only — the AOT backend has no `bytes`-returning random primitive yet.",
},
BuiltinSpec {
    names: &["__builtin_crypto_bytes_eq"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Constant-time byte comparison. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_xor_bytes"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Raw byte-wise XOR. Interpreter only — see std/hex.h#'s `xor` for the hex-string variant, which also isn't on AOT yet.",
},
BuiltinSpec {
    names: &["__builtin_crypto_sha256"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "SHA-256 (sha2 crate). Interpreter only — AOT has no crypto hashing at all yet (no C implementation in core.c).",
},
BuiltinSpec {
    names: &["__builtin_crypto_sha256_bytes"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "SHA-256 over raw bytes. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_sha512"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "SHA-512. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_sha1"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "SHA-1. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_md5"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "MD5. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_hmac_sha256"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "HMAC-SHA256. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_hmac_sha512"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "HMAC-SHA512. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hmac_sha256_b64url"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "HMAC-SHA256, base64url-encoded (backs std/jwt.h#'s HS256 signing). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_crypto_argon2_hash"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Argon2 password hashing. Not implemented on ANY backend yet — needs a real Argon2 dependency.",
},
BuiltinSpec {
    names: &["__builtin_crypto_argon2_verify"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Argon2 verification. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_crypto_blake3"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "BLAKE3 hashing. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_crypto_pbkdf2"],
    params: || vec![HType::Str, HType::Str, HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "PBKDF2 key derivation. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_hex_encode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Hex-encode text. Interpreter only — the AOT backend has no hex codec yet.",
},
BuiltinSpec {
    names: &["__builtin_hex_decode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Hex-decode text. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hex_encode_bytes"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Hex-encode raw bytes. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hex_xor"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "XOR two hex-encoded byte strings. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_base64url_encode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "base64url encoding (RFC 4648 §5, no padding). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_base64url_decode"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "base64url decoding. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_tcp_connect"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Open a real TCP client socket (std::net::TcpStream). Interpreter only — no socket support in core.c yet (beyond the existing one-shot `scan_port`).",
},
BuiltinSpec {
    names: &["__builtin_tcp_send"],
    params: || vec![HType::Int, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Write to a TCP socket opened by tcp_connect. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_tcp_recv"],
    params: || vec![HType::Int, HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Read from a TCP socket opened by tcp_connect. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_tcp_close"],
    params: || vec![HType::Int],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Close a TCP socket opened by tcp_connect. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_http_request"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Plain-HTTP/1.1 client request (std/http.h#, std/net_http.h#). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_atomic_add"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Named-counter atomic add (std/sync.h#). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_atomic_load"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Named-counter atomic load. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_atomic_store"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Named-counter atomic store. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_split_whitespace"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Split on any run of whitespace. Interpreter only — AOT's string ops don't cover this yet.",
},
BuiltinSpec {
    names: &["__builtin_str_replace_all"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Replace every occurrence (std/xml.h# entity decoding, std/fmt.h#). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_to_char_code"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "First character's Unicode codepoint. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_char_code_to_str"],
    params: || vec![HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Codepoint back to a one-character string. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_term_width"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Terminal width via `stty size`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_term_height"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Terminal height via `stty size`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_term_is_tty"],
    params: || vec![],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether stdout is a real terminal. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_join"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Path joining. Interpreter only — AOT has no std -> path support yet.",
},
BuiltinSpec {
    names: &["__builtin_path_stem"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Filename without extension. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_extension"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "File extension. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_parent"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parent directory. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_filename"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Last path component. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_is_absolute"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether a path is absolute. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_normalize"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Lexical `.`/`..` normalization. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_path_with_extension"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Replace a path's extension. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_process_run"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Run a shell command, capture stdout. Interpreter only — AOT has `shell`/`exec` builtins already; std/process.h# doesn't route through them yet.",
},
BuiltinSpec {
    names: &["__builtin_process_run_args"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Run a program with an explicit argv (no shell). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_process_spawn"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Background-spawn a command, return its PID. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_process_kill"],
    params: || vec![HType::Int],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Send SIGTERM to a PID. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_process_which"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Resolve a command via $PATH. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_cpu_count"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "/proc/cpuinfo CPU count. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_memory_total"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "/proc/meminfo total. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_memory_free"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "/proc/meminfo available. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_uptime"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "/proc/uptime. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_load_avg"],
    params: || vec![],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "/proc/loadavg 1-minute average. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_disk_total"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`df -k` total. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_disk_free"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`df -k` available. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_page_size"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`getconf PAGESIZE`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_get_uid"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`id -u`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_get_gid"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`id -g`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_get_ppid"],
    params: || vec![],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parent PID via `ps`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_is_64bit"],
    params: || vec![],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Pointer-width check. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_is_little_endian"],
    params: || vec![],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Endianness check. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_sysname"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`uname -s`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sys_machine"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`uname -m`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_os_home_dir"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "$HOME. Interpreter only — AOT has `env_get`, but std/os.h# doesn't route through it yet.",
},
BuiltinSpec {
    names: &["__builtin_os_temp_dir"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "System temp dir. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_os_is_root"],
    params: || vec![],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "uid == 0 check. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_os_kernel_version"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`uname -r`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_os_arch"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "CPU architecture. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_env_remove"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Unset an env var. Interpreter only — AOT has env_get/env_set but not remove.",
},
BuiltinSpec {
    names: &["__builtin_env_vars"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "All env vars as KEY=value strings. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_env_temp_dir"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "System temp dir. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_env_home"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "$HOME. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_year"],
    params: || vec![HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Calendar year from a unix timestamp (Howard Hinnant's algorithm). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_month"],
    params: || vec![HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Calendar month. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_day"],
    params: || vec![HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Calendar day. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_weekday"],
    params: || vec![HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Weekday abbreviation. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_add_days"],
    params: || vec![HType::Int, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Add whole days to a timestamp. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_add_hours"],
    params: || vec![HType::Int, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Add whole hours. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_diff_days"],
    params: || vec![HType::Int, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whole days between two timestamps. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_format"],
    params: || vec![HType::Int, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "strftime-lite formatting (%Y %m %d %H %M %S). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_date_parse"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parse \"YYYY-MM-DD[ HH:MM:SS]\". Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_conv_str_to_int"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parse int, 0 on failure. Interpreter only — AOT's parse_int has different (Option-shaped) semantics.",
},
BuiltinSpec {
    names: &["__builtin_conv_str_to_float"],
    params: || vec![HType::Str],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parse float, 0.0 on failure. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_conv_int_to_hex"],
    params: || vec![HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Int to hex string. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_conv_float_to_int"],
    params: || vec![HType::F64],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Truncating float-to-int (math_trunc stays float-in-float-out). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_read_bytes"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Read a file as raw bytes. Interpreter only — AOT's fs_read is text-only.",
},
BuiltinSpec {
    names: &["__builtin_fs_write_bytes"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Write raw bytes to a file. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_read_lines"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Read a file as an array of lines. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_walk"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Recursive directory walk. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_modified_time"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "File mtime as a unix timestamp. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_temp_file"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Create a uniquely-named temp file. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_list_dir"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "List a directory's entries. Interpreter only — AOT has no directory-listing builtin yet.",
},
BuiltinSpec {
    names: &["__builtin_sort_by"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Comparator-based sort (invokes an H# closure per comparison). Interpreter only — needs closure-calling support from codegen's native-builtin dispatch, which doesn't exist yet.",
},
BuiltinSpec {
    names: &["__builtin_regex_find_all"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "All non-overlapping regex matches. Interpreter only (regex.c/libpcre2 was removed from the AOT runtime — see codegen.rs's emit_binary_with_machine).",
},
BuiltinSpec {
    names: &["__builtin_regex_replace_all"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Replace every regex match. Interpreter only (see __builtin_regex_find_all's doc).",
},
BuiltinSpec {
    names: &["__builtin_regex_split"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Split on a regex/whitespace pattern. Interpreter only (see __builtin_regex_find_all's doc).",
},
BuiltinSpec {
    names: &["__builtin_db_open"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Open a sqlite3 connection (shells out to the `sqlite3` CLI). Interpreter only (sqlite.c was removed from the AOT runtime — see codegen.rs's emit_binary_with_machine).",
},
BuiltinSpec {
    names: &["__builtin_db_exec"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Execute a SQL statement. Interpreter only (see __builtin_db_open's doc).",
},
BuiltinSpec {
    names: &["__builtin_db_query"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Run a SQL query, get rows back. Interpreter only (see __builtin_db_open's doc).",
},
BuiltinSpec {
    names: &["__builtin_db_close"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Close a sqlite3 connection. Interpreter only (see __builtin_db_open's doc).",
},
BuiltinSpec {
    names: &["__builtin_bytes_from_ints"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Build raw bytes from an [int] array of 0-255 values (needed for binary formats like MessagePack, since H# strings must be valid UTF-8). Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_bytes_to_ints"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Inverse of bytes_from_ints. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_bytes_concat"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Concatenate two byte buffers. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_bytes_len"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Byte buffer length. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_bytes_to_string"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Lossy UTF-8 decode of a byte buffer. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_uuid_is_valid"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Structural UUID validation. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_io_read_line"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Read a line from stdin. Interpreter only — AOT programs currently have no stdin-reading builtin at all.",
},
BuiltinSpec {
    names: &["__builtin_io_read_char"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Read one byte from stdin. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_io_write_no_nl"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Write to stdout without a trailing newline. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_io_flush"],
    params: || vec![],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Flush stdout. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_asin"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "arcsine. Interpreter only — AOT's math builtins cover sin/cos/tan/sqrt/floor/ceil/pow only.",
},
BuiltinSpec {
    names: &["__builtin_math_acos"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "arccosine. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_atan"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "arctangent. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_atan2"],
    params: || vec![HType::F64, HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "two-argument arctangent. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_round"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "round to nearest. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_trunc"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "truncate toward zero. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_log"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "natural log. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_log2"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "base-2 log. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_log10"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "base-10 log. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_math_exp"],
    params: || vec![HType::F64],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "e^x. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_split"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Split on a separator. Interpreter only — AOT has no array-returning string split builtin yet.",
},
BuiltinSpec {
    names: &["__builtin_str_join"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Join an array with a separator. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_reverse"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Reverse a string. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_count"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Count non-overlapping occurrences of a substring. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_index_of"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Index of the first occurrence of a substring, -1 if absent. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_is_numeric"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether every character is an ASCII digit. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_str_trim_start"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Trim leading whitespace only. Interpreter only — AOT's `trim`/`str_trim` trims both ends.",
},
BuiltinSpec {
    names: &["__builtin_str_trim_end"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Trim trailing whitespace only. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_parse"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parse a JSON string into a queryable value. Interpreter only — AOT has a much smaller json_get/json_set_str pair, no general parse/stringify.",
},
BuiltinSpec {
    names: &["__builtin_json_parse_array"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Parse a JSON array. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_stringify"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Serialize a value to a JSON string. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_stringify_pretty"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Pretty-printed JSON serialization. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_empty_object"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "A new empty JSON object value. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_set"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Set a key on a JSON object, returning the updated value. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_get_str"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get a string field. Interpreter only (AOT has a similarly-named but differently-shaped `json_get_str`/`json_get` pair for its own, much smaller JSON API — not compatible with std/json.h#'s value model).",
},
BuiltinSpec {
    names: &["__builtin_json_get_int"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get an int field. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_get_float"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get a float field. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_get_bool"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get a bool field. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_get_obj"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get a nested object field. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_get_arr"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Get an array field. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_has_key"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether an object has a key. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_is_null"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether a value is JSON null. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_query"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Dotted-path query into a JSON value. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_as_int"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Coerce a JSON value to int. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_json_as_str"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Coerce a JSON value to string. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_new"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Create a new hashmap. Interpreter only — AOT has no generic hashmap/hashset data structure in core.c yet.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_insert"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Insert into a hashmap, returning the updated map. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_get"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Look up a hashmap key. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_remove"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Remove a hashmap key, returning the updated map. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_contains"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether a hashmap has a key. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_keys"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "All keys in a hashmap. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_values"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "All values in a hashmap. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashmap_len"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Number of entries in a hashmap. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_new"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Create a new hashset. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_insert"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Insert into a hashset, returning the updated set. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_remove"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Remove from a hashset, returning the updated set. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_contains"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Whether a hashset has a value. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_len"],
    params: || vec![HType::Str],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Number of entries in a hashset. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_hashset_to_array"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "A hashset's entries as an array. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_sort_ints"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Sort an [int] array, returning a new sorted array. Interpreter only — AOT has no array-sorting builtin yet.",
},
BuiltinSpec {
    names: &["__builtin_sort_strings"],
    params: || vec![HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Sort a [string] array. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_test_fail"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "std/test.h#'s test-failure helper. Interpreter only — there is no test-runner concept on the AOT backend at all (tests run via `hsharp preview`/the interpreter).",
},
BuiltinSpec {
    names: &["__builtin_test_skip"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "std/test.h#'s test-skip helper. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_fs_copy"],
    params: || vec![HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Copy a file. Interpreter only — AOT has no file-copy builtin yet.",
},
BuiltinSpec {
    names: &["__builtin_fs_rmdir"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "Remove an empty directory (non-recursive). Interpreter only — AOT only has the recursive `fs_remove_dir`, which this deliberately doesn't alias to (different, more destructive semantics).",
},
BuiltinSpec {
    names: &["__builtin_sys_kernel_version"],
    params: || vec![],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[Backend::Interpreter],
    doc: "`uname -r`. Interpreter only.",
},
BuiltinSpec {
    names: &["__builtin_db_begin"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Begin a SQL transaction. Not implemented on ANY backend yet — std/db.h#'s `open`/`exec`/`query`/`close` are real (via the sqlite3 CLI, interpreter only), but transactions aren't.",
},
BuiltinSpec {
    names: &["__builtin_db_commit"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Commit a SQL transaction. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_rollback"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Roll back a SQL transaction. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_ping"],
    params: || vec![HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Check a database connection is alive. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_exec_params"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Parameterized SQL execute. Not implemented on any backend yet — see std/db.h#'s module doc comment; only unparameterized `exec` is real.",
},
BuiltinSpec {
    names: &["__builtin_db_query_params"],
    params: || vec![HType::Str, HType::Str, HType::Str],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[],
    doc: "Parameterized SQL query. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_col_bool"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Typed column accessor. Not implemented on any backend yet — std/db.h#'s `query` returns raw text rows, not a typed row/column API.",
},
BuiltinSpec {
    names: &["__builtin_db_col_float"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::F64,
    c_symbol: None,
    backends: &[],
    doc: "Typed column accessor. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_col_int"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Int,
    c_symbol: None,
    backends: &[],
    doc: "Typed column accessor. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_col_is_null"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Bool,
    c_symbol: None,
    backends: &[],
    doc: "Typed column accessor. Not implemented on any backend yet.",
},
BuiltinSpec {
    names: &["__builtin_db_col_str"],
    params: || vec![HType::Str, HType::Int],
    ret: || HType::Str,
    c_symbol: None,
    backends: &[],
    doc: "Typed column accessor. Not implemented on any backend yet.",
},
];

/// Look up a builtin spec by any of its names.
pub fn find(name: &str) -> Option<&'static BuiltinSpec> {
    BUILTINS.iter().find(|b| b.names.contains(&name))
}

/// Does `name` have a working implementation on `backend`?
/// Returns `true` for any name not in `BUILTINS` at all (user-defined
/// functions aren't builtins and aren't restricted by this table).
pub fn supported_on(name: &str, backend: Backend) -> bool {
    match find(name) {
        Some(spec) => spec.backends.contains(&backend),
        None => true,
    }
}

/// AOT/LLVM-side counterpart of `hsharp-interpreter::helpers::
/// resolve_builtin_dunder` — see that function's doc comment for the
/// full interpreter/AOT-parity story this exists to fix.
///
/// Every `std/*.h#` wrapper function (loaded via
/// `ModuleResolver::resolve_std_import` in `modules.rs`) calls a
/// `__builtin_*`-prefixed intrinsic internally. Most of those
/// intrinsics correspond to a `hsh_*` C function that **already
/// existed** in `core.c` and already had a plain (non-prefixed)
/// dispatch arm in `codegen.rs`'s `call_fn` — they just had no
/// `__builtin_`-prefixed alias, since that whole naming convention was
/// introduced by the interpreter-side stdlib work and never
/// back-ported here. This function is that missing alias table.
///
/// Returns `None` for anything that genuinely has no AOT
/// implementation yet — those are listed as `Backend::Interpreter`-only
/// entries in `BUILTINS` above instead, so `features::
/// check_module_features` gives a clean "not supported by the LLVM
/// backend" diagnostic (with a doc string explaining the gap) instead
/// of `call_fn` falling through to a raw `UndefinedFn` codegen error.
pub fn resolve_builtin_dunder_llvm(name: &str) -> Option<&'static str> {
    let stripped = name.strip_prefix("__builtin_")?;
    Some(match stripped {
        // ── already real on this backend — see codegen.rs's `call_fn`
        // for each of these arms; this table just adds the missing
        // `__builtin_` spelling ────────────────────────────────────────
        "uuid_v4"          => "uuid_v4",
        "base64_encode"    => "base64_encode",
        "base64_decode"    => "base64_decode",
        "url_encode"       => "url_encode",
        "url_decode"       => "url_decode",
        "env_get"          => "env_get",
        "env_set"          => "env_set",
        "env_args"         => "env_args",
        "fs_read"          => "fs_read",
        "fs_write"         => "fs_write",
        "fs_exists"        => "fs_exists",
        "fs_mkdir"         => "fs_mkdir_all",
        "fs_size"          => "fs_size",
        "fs_remove"        => "fs_remove",
        "fs_rename"        => "fs_rename",
        "fs_is_dir"        => "is_dir",
        "fs_is_file"       => "fs_is_file",
        "fs_append"        => "fs_append",
        "fs_rmdir_all"     => "fs_remove_dir",
        "fs_cwd"           => "cwd",
        "fs_chdir"         => "fs_chdir",
        "crypto_random_int" => "random_int",
        "os_hostname"      => "hostname",
        "os_pid"           => "getpid",
        "os_username"      => "os_username",
        "os_platform"      => "os_platform",
        "sys_get_pid"      => "getpid",
        "sys_hostname"     => "hostname",
        "time_now_unix"    => "now_unix",
        "time_now_ms"      => "now_ms",
        "time_sleep_ms"    => "sleep_ms",
        // `hsh_scan_port_net(host, port, timeout_ms)` — same argument
        // order `std/tcp.h#`'s `scan_port` already uses.
        "tcp_scan_port"    => "scan_port",
        // ── math (only the subset with a real AOT arm — see codegen.rs;
        // asin/acos/atan/atan2/round/trunc/log/log2/log10/exp are
        // genuine gaps, registered below in BUILTINS instead) ──────────
        "math_sin" => "math_sin", "math_cos" => "math_cos", "math_tan" => "math_tan",
        "math_sqrt" => "math_sqrt", "math_floor" => "math_floor", "math_ceil" => "math_ceil",
        "math_pow" => "math_pow",
        // ── strings (only the subset with a real AOT arm) ───────────────
        "str_trim"    => "str_trim",
        "str_to_upper" => "to_upper",
        "str_to_lower" => "to_lower",
        "str_replace"  => "str_replace",
        // ── regex / db — these route into arms whose C implementation
        // (regex.c / sqlite.c) was intentionally removed (see
        // `emit_binary_with_machine`'s `needs_regex`/`needs_db` early
        // bail-out, and `is_bare_regex_builtin`/`is_bare_db_builtin`'s
        // doc comments) — bridging them here means that early, clear
        // "AOT doesn't support regex::/db:: yet" error fires (since the
        // scanner recognizes these `__builtin_` spellings too), instead
        // of the call falling through to `UndefinedFn` before ever
        // reaching that check.
        "regex_match"   => "regex_match",
        "regex_find"    => "regex_find",
        "regex_replace" => "regex_replace",
        "db_open"  => "sqlite_open",
        "db_exec"  => "sqlite_exec",
        "db_query" => "sqlite_query",
        "db_close" => "sqlite_close",
        "path_exists"    => "fs_exists",
        "process_shell"  => "shell",
        _ => return None,
    })
}
