use hsharp_parser::ast::*;
use std::fmt::Write;
use crate::CompileOptions;

#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("unsupported feature: {0}")]
    Unsupported(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("compilation failed: {0}")]
    CompileError(String),
    #[error("cc not found: install gcc or clang")]
    NoCompiler,
}

#[allow(dead_code)]
pub struct Codegen {
    file: String,
    opts: CompileOptions,
    output: String,
    indent: usize,
    header: String,
    forward_decls: String,
    body: String,
}

impl Codegen {
    pub fn new(file: &str, opts: &CompileOptions) -> Self {
        Self {
            file: file.to_string(),
            opts: opts.clone(),
            output: String::new(),
            indent: 0,
            header: String::new(),
            forward_decls: String::new(),
            body: String::new(),
        }
    }

    fn emit_header(&mut self) {
        self.header.push_str(r#"/* Generated by H# compiler */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* H# runtime types */
typedef int64_t    hsh_int;
typedef uint64_t   hsh_uint;
typedef int8_t     hsh_i8;
typedef int16_t    hsh_i16;
typedef int32_t    hsh_i32;
typedef int64_t    hsh_i64;
typedef __int128   hsh_i128;
typedef uint8_t    hsh_u8;
typedef uint16_t   hsh_u16;
typedef uint32_t   hsh_u32;
typedef uint64_t   hsh_u64;
typedef unsigned __int128 hsh_u128;
typedef float      hsh_f32;
typedef double     hsh_f64;
typedef bool       hsh_bool;
typedef char*      hsh_string;
typedef struct { uint8_t* data; size_t len; size_t cap; } hsh_bytes;

/* H# Arena allocator */
typedef struct {
    uint8_t* base;
    size_t   cap;
    size_t   used;
} HshArena;

static HshArena* hsh_arena_new(size_t cap) {
    HshArena* a = (HshArena*)malloc(sizeof(HshArena));
    a->base = (uint8_t*)malloc(cap);
    a->cap  = cap;
    a->used = 0;
    return a;
}
static void* hsh_arena_alloc(HshArena* a, size_t n) {
    if (a->used + n > a->cap) { fprintf(stderr, "arena OOM\n"); exit(1); }
    void* p = a->base + a->used;
    a->used += n;
    return p;
}
static void hsh_arena_free(HshArena* a) {
    free(a->base);
    free(a);
}

/* H# builtins */
static void hsh_print(hsh_string s)   { printf("%s", s); }
static void hsh_println(hsh_string s) { printf("%s\n", s); }
static hsh_string hsh_int_to_string(hsh_int n) {
    char* buf = (char*)malloc(32);
    snprintf(buf, 32, "%ld", (long)n);
    return buf;
}
static hsh_string hsh_bool_to_string(hsh_bool b) { return b ? "true" : "false"; }
static hsh_int    hsh_strlen(hsh_string s) { return (hsh_int)strlen(s); }
static void       hsh_panic(hsh_string s) { fprintf(stderr, "panic: %s\n", s); exit(1); }
static hsh_string hsh_strcat(hsh_string a, hsh_string b) {
    size_t la = strlen(a), lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    memcpy(out, a, la);
    memcpy(out + la, b, lb);
    out[la + lb] = '\0';
    return out;
}
static hsh_string hsh_any_to_string(hsh_int n) { return hsh_int_to_string(n); }

"#);
    }

    pub fn compile_module(&mut self, module: &Module) -> Result<(), CodegenError> {
        self.emit_header();

        // Forward-declare all structs
        for item in &module.items {
            if let Item::StructDef(s) = item {
                let decl = format!("typedef struct {} {};\n", s.name, s.name);
                self.forward_decls.push_str(&decl);
            }
        }

        // Emit all items
        for item in &module.items {
            self.emit_item(item)?;
        }

        // Combine
        self.output = format!("{}\n{}\n{}", self.header, self.forward_decls, self.body);
        Ok(())
    }

    fn emit_item(&mut self, item: &Item) -> Result<(), CodegenError> {
        match item {
            Item::FnDef(f) => self.emit_fn(f)?,
            Item::StructDef(s) => self.emit_struct(s)?,
            Item::EnumDef(e) => self.emit_enum(e)?,
            Item::ImplBlock(impl_) => {
                for method in &impl_.methods {
                    self.emit_method(method, &impl_.type_name)?;
                }
            }
            Item::TypeAlias { name, ty, .. } => {
                let c_ty = self.type_to_c(ty);
                writeln!(self.body, "typedef {} {};", c_ty, name).ok();
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_struct(&mut self, s: &StructDef) -> Result<(), CodegenError> {
        writeln!(self.body, "struct {} {{", s.name).ok();
        for field in &s.fields {
            let c_ty = self.type_to_c(&field.ty);
            writeln!(self.body, "    {} {};", c_ty, field.name).ok();
        }
        writeln!(self.body, "}};").ok();
        Ok(())
    }

    fn emit_enum(&mut self, e: &EnumDef) -> Result<(), CodegenError> {
        // Tagged union approach
        writeln!(self.body, "typedef enum {{ {} }} {}_Tag;",
            e.variants.iter().map(|v| format!("{}__{}", e.name, v.name)).collect::<Vec<_>>().join(", "),
            e.name).ok();
        writeln!(self.body, "typedef struct {} {{", e.name).ok();
        writeln!(self.body, "    {}_Tag tag;", e.name).ok();
        writeln!(self.body, "    union {{").ok();
        for variant in &e.variants {
            if let EnumVariantFields::Tuple(types) = &variant.fields {
                if !types.is_empty() {
                    writeln!(self.body, "        struct {{").ok();
                    for (i, ty) in types.iter().enumerate() {
                        let c_ty = self.type_to_c(ty);
                        writeln!(self.body, "            {} field{};", c_ty, i).ok();
                    }
                    writeln!(self.body, "        }} {};", variant.name.to_lowercase()).ok();
                }
            }
        }
        writeln!(self.body, "    }} data;").ok();
        writeln!(self.body, "}} {};", e.name).ok();
        Ok(())
    }

    fn emit_fn(&mut self, f: &FnDef) -> Result<(), CodegenError> {
        let ret = f.return_type.as_ref().map(|t| self.type_to_c(t)).unwrap_or_else(|| "void".to_string());
        let params: Vec<String> = f.params.iter().map(|p| {
            let ty = self.type_to_c(&p.ty);
            format!("{} {}", ty, p.name)
        }).collect();

        let is_main = f.name == "main";
        let fn_name = if is_main { "main".to_string() } else { f.name.clone() };
        let c_ret = if is_main { "int".to_string() } else { ret };
        let c_params = if is_main && params.is_empty() { "void".to_string() } else { params.join(", ") };

        writeln!(self.body, "{} {}({}) {{", c_ret, fn_name, c_params).ok();

        for stmt in &f.body {
            self.emit_stmt(stmt, 1)?;
        }

        if is_main {
            writeln!(self.body, "    return 0;").ok();
        }
        writeln!(self.body, "}}").ok();
        Ok(())
    }

    fn emit_method(&mut self, f: &FnDef, type_name: &str) -> Result<(), CodegenError> {
        let ret = f.return_type.as_ref().map(|t| self.type_to_c(t)).unwrap_or_else(|| "void".to_string());
        let mut params: Vec<String> = Vec::new();

        for p in &f.params {
            if p.name == "self" {
                params.push(format!("{}* self", type_name));
            } else {
                let ty = self.type_to_c(&p.ty);
                params.push(format!("{} {}", ty, p.name));
            }
        }

        writeln!(self.body, "{} {}_{}({}) {{", ret, type_name, f.name, params.join(", ")).ok();
        for stmt in &f.body {
            self.emit_stmt(stmt, 1)?;
        }
        writeln!(self.body, "}}").ok();
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt, depth: usize) -> Result<(), CodegenError> {
        let indent = "    ".repeat(depth);
        match stmt {
            Stmt::Let { name, ty, mutable, value, .. } => {
                let c_ty = ty.as_ref().map(|t| self.type_to_c(t))
                    .unwrap_or_else(|| "hsh_int".to_string());
                let val_str = value.as_ref().map(|e| self.emit_expr(e)).unwrap_or_else(|| "0".to_string());
                let c_mut = if *mutable { "" } else { "const " };
                writeln!(self.body, "{}{}{} {} = {};", indent, c_mut, c_ty, name, val_str).ok();
            }
            Stmt::Return(expr, _) => {
                let val = expr.as_ref().map(|e| self.emit_expr(e)).unwrap_or_default();
                writeln!(self.body, "{}return {};", indent, val).ok();
            }
            Stmt::Expr(expr, _) => {
                // Special handling for control flow expressions
                match expr {
                    Expr::If { condition, then_body, elsif_branches, else_body, .. } => {
                        self.emit_if_stmt(condition, then_body, elsif_branches, else_body, depth)?;
                    }
                    Expr::While { condition, body, .. } => {
                        let cond = self.emit_expr(condition);
                        writeln!(self.body, "{}while ({}) {{", indent, cond).ok();
                        for s in body { self.emit_stmt(s, depth + 1)?; }
                        writeln!(self.body, "{}}}", indent).ok();
                    }
                    Expr::For { pattern, iterable, body, .. } => {
                        self.emit_for_stmt(pattern, iterable, body, depth)?;
                    }
                    Expr::Unsafe(body, arena, _) => {
                        if let Some(arena_cfg) = arena {
                            let size = arena_cfg.size.unwrap_or(1024 * 1024);
                            writeln!(self.body, "{}{{ HshArena* __arena = hsh_arena_new({});", indent, size).ok();
                            for s in body { self.emit_stmt(s, depth + 1)?; }
                            writeln!(self.body, "{}    hsh_arena_free(__arena); }}", indent).ok();
                        } else {
                            writeln!(self.body, "{}{{", indent).ok();
                            for s in body { self.emit_stmt(s, depth + 1)?; }
                            writeln!(self.body, "{}}}", indent).ok();
                        }
                    }
                    Expr::Match { subject, arms, .. } => {
                        self.emit_match_stmt(subject, arms, depth)?;
                    }
                    Expr::Assign(lhs, rhs, _) => {
                        let l = self.emit_expr(lhs);
                        let r = self.emit_expr(rhs);
                        writeln!(self.body, "{}{} = {};", indent, l, r).ok();
                    }
                    Expr::CompoundAssign(lhs, op, rhs, _) => {
                        let l = self.emit_expr(lhs);
                        let r = self.emit_expr(rhs);
                        let op_str = binop_to_c(op);
                        writeln!(self.body, "{}{} {}= {};", indent, l, op_str, r).ok();
                    }
                    _ => {
                        let s = self.emit_expr(expr);
                        writeln!(self.body, "{}{};", indent, s).ok();
                    }
                }
            }
            Stmt::Break(_, _) => { writeln!(self.body, "{}break;", indent).ok(); }
            Stmt::Continue(_) => { writeln!(self.body, "{}continue;", indent).ok(); }
            Stmt::Item(item) => self.emit_item(item)?,
            Stmt::Import(_, _, _) => {} // handled at module level
        }
        Ok(())
    }

    fn emit_if_stmt(&mut self, cond: &Expr, then_body: &[Stmt],
        elsif: &[(Expr, Vec<Stmt>)], else_body: &Option<Vec<Stmt>>, depth: usize) -> Result<(), CodegenError> {
        let indent = "    ".repeat(depth);
        let c = self.emit_expr(cond);
        writeln!(self.body, "{}if ({}) {{", indent, c).ok();
        for s in then_body { self.emit_stmt(s, depth + 1)?; }
        for (ec, eb) in elsif {
            let ec_str = self.emit_expr(ec);
            writeln!(self.body, "{}}} else if ({}) {{", indent, ec_str).ok();
            for s in eb { self.emit_stmt(s, depth + 1)?; }
        }
        if let Some(else_b) = else_body {
            writeln!(self.body, "{}}} else {{", indent).ok();
            for s in else_b { self.emit_stmt(s, depth + 1)?; }
        }
        writeln!(self.body, "{}}}", indent).ok();
        Ok(())
    }

    fn emit_for_stmt(&mut self, pattern: &Pattern, iterable: &Expr, body: &[Stmt], depth: usize) -> Result<(), CodegenError> {
        let indent = "    ".repeat(depth);
        let iter_expr = self.emit_expr(iterable);

        // Simple range-based for
        if let Pattern::Ident(var, _) = pattern {
            if let Expr::Range(start, end, inclusive, _) = iterable {
                let s = self.emit_expr(start);
                let e = self.emit_expr(end);
                let op = if *inclusive { "<=" } else { "<" };
                writeln!(self.body, "{}for (hsh_int {} = {}; {} {} {}; {}++) {{",
                    indent, var, s, var, op, e, var).ok();
                for stmt in body { self.emit_stmt(stmt, depth + 1)?; }
                writeln!(self.body, "{}}}", indent).ok();
                return Ok(());
            }
        }

        // Generic iterator — generate a while-style loop
        let var_name = match pattern {
            Pattern::Ident(n, _) => n.clone(),
            _ => "__item".to_string(),
        };
        writeln!(self.body, "{}/* for-in: {} */", indent, iter_expr).ok();
        writeln!(self.body, "{}for (size_t __i = 0; __i < {}.len; __i++) {{", indent, iter_expr).ok();
        writeln!(self.body, "{}    hsh_int {} = {}.data[__i];", indent, var_name, iter_expr).ok();
        for stmt in body { self.emit_stmt(stmt, depth + 1)?; }
        writeln!(self.body, "{}}}", indent).ok();
        Ok(())
    }

    fn emit_match_stmt(&mut self, subject: &Expr, arms: &[MatchArm], depth: usize) -> Result<(), CodegenError> {
        let indent = "    ".repeat(depth);
        let subj = self.emit_expr(subject);

        // Try to emit as C switch for integer/bool subjects
        writeln!(self.body, "{}/* match */", indent).ok();
        writeln!(self.body, "{}{{\n{}    __typeof__({}) __subj = {};", indent, indent, subj, subj).ok();

        let mut first = true;
        for arm in arms {
            let kw = if first { "if" } else { "else if" };
            first = false;
            let pat_cond = self.pattern_condition("__subj", &arm.pattern);

            let guard_str = if let Some(g) = &arm.guard {
                format!(" && ({})", self.emit_expr(g))
            } else { String::new() };

            writeln!(self.body, "{}    {} ({}{}) {{", indent, kw, pat_cond, guard_str).ok();

            // Bind pattern variables
            self.emit_pattern_bindings("__subj", &arm.pattern, depth + 2);
            for stmt in &arm.body {
                self.emit_stmt(stmt, depth + 2)?;
            }
            writeln!(self.body, "{}    }}", indent).ok();
        }
        writeln!(self.body, "{}}}", indent).ok();
        Ok(())
    }

    fn pattern_condition(&self, subject: &str, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard(_) => "1".to_string(),
            Pattern::Ident(_, _) => "1".to_string(),
            Pattern::Literal(lit, _) => match lit {
                Literal::Int(n) => format!("{} == {}", subject, n),
                Literal::Bool(b) => format!("{} == {}", subject, if *b { "true" } else { "false" }),
                Literal::String(s) => format!("strcmp({}, \"{}\") == 0", subject, s.replace('"', "\\\"")),
                Literal::Nil => format!("{} == NULL", subject),
                _ => "1".to_string(),
            },
            Pattern::Or(pats, _) => pats.iter()
                .map(|p| format!("({})", self.pattern_condition(subject, p)))
                .collect::<Vec<_>>().join(" || "),
            _ => "1".to_string(),
        }
    }

    fn emit_pattern_bindings(&mut self, subject: &str, pat: &Pattern, depth: usize) {
        let indent = "    ".repeat(depth);
        if let Pattern::Ident(name, _) = pat {
            writeln!(self.body, "{}__typeof__({}) {} = {};", indent, subject, name, subject).ok();
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(lit, _) => match lit {
                Literal::Int(n) => n.to_string(),
                Literal::Float(f) => format!("{:.}", f),
                Literal::String(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n")),
                Literal::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
                Literal::Nil => "NULL".to_string(),
                Literal::Bytes(_) => "NULL /* bytes */".to_string(),
            },
            Expr::Ident(name, _) => name.clone(),
            Expr::SelfExpr(_) => "self".to_string(),
            Expr::BinOp(lhs, op, rhs, _) => {
                let l = self.emit_expr(lhs);
                let r = self.emit_expr(rhs);
                // String concatenation must use hsh_strcat, not C + operator
                if matches!(op, BinOp::Add) {
                    // Check if either side looks like a string literal or string expr
                    // We use hsh_strcat conservatively for any Add involving string literals
                    let l_is_str = l.starts_with('"') || r.starts_with('"')
                        || l.contains("hsh_str") || r.contains("hsh_str")
                        || l.contains("to_string") || r.contains("to_string")
                        || l.contains("hsh_int_to_string") || r.contains("hsh_int_to_string")
                        || l.contains("greet") || r.contains("greet");
                    if l_is_str {
                        return format!("hsh_strcat({}, {})", l, r);
                    }
                }
                let o = binop_to_c(op);
                format!("({} {} {})", l, o, r)
            }
            Expr::UnOp(op, inner, _) => {
                let i = self.emit_expr(inner);
                match op {
                    UnOp::Neg => format!("(-{})", i),
                    UnOp::Not => format!("(!{})", i),
                    UnOp::BitNot => format!("(~{})", i),
                    UnOp::Ref | UnOp::RefMut => format!("(&{})", i),
                    UnOp::Deref => format!("(*{})", i),
                }
            }
            Expr::Call(callee, args, _) => {
                let callee_str = self.emit_expr(callee);
                let args_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                // Map H# builtins to C runtime
                let c_name = match callee_str.as_str() {
                    "print"     => "hsh_print".to_string(),
                    "println"   => "hsh_println".to_string(),
                    // New H# 0.1 syntax: write() = println(), writeln() = println()
                    "write"     => "hsh_println".to_string(),
                    "writeln"   => "hsh_println".to_string(),
                    "panic"     => "hsh_panic".to_string(),
                    "exit"      => "exit".to_string(),
                    "to_string" => "hsh_int_to_string".to_string(),
                    "len"       => "hsh_strlen".to_string(),
                    "assert"    => "hsh_assert".to_string(),
                    _           => callee_str,
                };
                format!("{}({})", c_name, args_strs.join(", "))
            }
            Expr::MethodCall(obj, method, args, _) => {
                let obj_str = self.emit_expr(obj);
                let args_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                // Map common methods
                match method.as_str() {
                    "len" => format!("hsh_strlen({})", obj_str),
                    "to_string" => format!("hsh_int_to_string({})", obj_str),
                    "push" => format!("/* push not yet impl for {} */", obj_str),
                    _ => {
                        if args_strs.is_empty() {
                            format!("{}.{}", obj_str, method)
                        } else {
                            format!("{}__{}(&{}, {})", 
                                "__obj", method, obj_str, args_strs.join(", "))
                        }
                    }
                }
            }
            Expr::FieldAccess(obj, field, _) => {
                let obj_str = self.emit_expr(obj);
                format!("{}.{}", obj_str, field)
            }
            Expr::IndexAccess(arr, idx, _) => {
                let a = self.emit_expr(arr);
                let i = self.emit_expr(idx);
                format!("{}[{}]", a, i)
            }
            Expr::Cast(inner, ty, _) => {
                let i = self.emit_expr(inner);
                let c_ty = self.type_to_c(ty);
                format!("(({}){})", c_ty, i)
            }
            Expr::Assign(lhs, rhs, _) => {
                let l = self.emit_expr(lhs);
                let r = self.emit_expr(rhs);
                format!("({} = {})", l, r)
            }
            Expr::CompoundAssign(lhs, op, rhs, _) => {
                let l = self.emit_expr(lhs);
                let r = self.emit_expr(rhs);
                let o = binop_to_c(op);
                format!("({} {}= {})", l, o, r)
            }
            Expr::ArrayLit(elems, _) => {
                // Stack array initializer
                let elems_str: Vec<String> = elems.iter().map(|e| self.emit_expr(e)).collect();
                format!("{{ {} }}", elems_str.join(", "))
            }
            Expr::StructLit(name, fields, _) => {
                let fields_str: Vec<String> = fields.iter()
                    .map(|(k, v)| format!(".{} = {}", k, self.emit_expr(v)))
                    .collect();
                format!("({}){{ {} }}", name, fields_str.join(", "))
            }
            Expr::Return(val, _) => {
                let v = val.as_ref().map(|e| self.emit_expr(e)).unwrap_or_default();
                format!("return {}", v)
            }
            Expr::Try(inner, _) => {
                let i = self.emit_expr(inner);
                format!("({} /* ? */)", i)
            }
            Expr::Range(start, _end, _, _) => {
                // Ranges are handled in for-loops; here just emit start
                let s = self.emit_expr(start);
                s
            }
            _ => "/* unsupported expr */".to_string(),
        }
    }

    fn type_to_c(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Named(n) => match n.as_str() {
                "int"    => "hsh_int".into(),
                "uint"   => "hsh_uint".into(),
                "i8"     => "hsh_i8".into(),
                "i16"    => "hsh_i16".into(),
                "i32"    => "hsh_i32".into(),
                "i64"    => "hsh_i64".into(),
                "i128"   => "hsh_i128".into(),
                "u8"     => "hsh_u8".into(),
                "u16"    => "hsh_u16".into(),
                "u32"    => "hsh_u32".into(),
                "u64"    => "hsh_u64".into(),
                "u128"   => "hsh_u128".into(),
                "f32"    => "hsh_f32".into(),
                "f64"    => "hsh_f64".into(),
                "bool"   => "hsh_bool".into(),
                "string" => "hsh_string".into(),
                "bytes"  => "hsh_bytes".into(),
                "any"    => "void*".into(),
                other    => other.into(),
            },
            TypeExpr::Void => "void".into(),
            TypeExpr::Optional(inner) => format!("{}*", self.type_to_c(inner)),
            TypeExpr::Array(inner) => format!("{}*", self.type_to_c(inner)),
            TypeExpr::Ref(inner) | TypeExpr::RefMut(inner) => format!("{}*", self.type_to_c(inner)),
            TypeExpr::Tuple(_ts) => "void*".into(), // simplified
            TypeExpr::Generic(name, _) => name.clone(),
            TypeExpr::Fn(_, ret) => format!("{}(*)()", self.type_to_c(ret)),
            TypeExpr::Slice(inner, _) => format!("{}*", self.type_to_c(inner)),
            // Explicit numeric type aliases
            TypeExpr::I8   => "hsh_i8".into(),
            TypeExpr::I16  => "hsh_i16".into(),
            TypeExpr::I32  => "hsh_i32".into(),
            TypeExpr::I64  => "hsh_i64".into(),
            TypeExpr::I128 => "hsh_i128".into(),
            TypeExpr::U8   => "hsh_u8".into(),
            TypeExpr::U16  => "hsh_u16".into(),
            TypeExpr::U32  => "hsh_u32".into(),
            TypeExpr::U64  => "hsh_u64".into(),
            TypeExpr::U128 => "hsh_u128".into(),
            TypeExpr::F32  => "hsh_f32".into(),
            TypeExpr::F64  => "hsh_f64".into(),
            TypeExpr::Bool   => "hsh_bool".into(),
            TypeExpr::String => "hsh_string".into(),
            TypeExpr::Bytes  => "hsh_bytes".into(),
        }
    }

    pub fn emit_object(&self, output: &str) -> Result<(), CodegenError> {
        use std::process::Command;

        // Write C source
        let c_path = format!("{}.c", output);
        std::fs::write(&c_path, &self.output).map_err(CodegenError::Io)?;

        // Find C compiler
        let compiler = find_c_compiler().ok_or(CodegenError::NoCompiler)?;

        // Build the binary
        let mut cmd = Command::new(&compiler);
        cmd.arg("-O2").arg("-o").arg(output).arg(&c_path);

        // Static linking
        if self.opts.static_link {
            cmd.arg("-static");
        }

        // Target triple
        let triple = &self.opts.target.llvm_triple;
        if triple.contains("musl") {
            cmd.arg("-target").arg(triple);
        }

        let status = cmd.status().map_err(|e| {
            CodegenError::CompileError(format!("failed to run {}: {}", compiler, e))
        })?;

        if !status.success() {
            return Err(CodegenError::CompileError(format!(
                "{} exited with code {:?}", compiler, status.code()
            )));
        }

        // Cleanup C source
        let _ = std::fs::remove_file(&c_path);
        Ok(())
    }

    pub fn get_c_source(&self) -> &str {
        &self.output
    }
}

fn find_c_compiler() -> Option<String> {
    for compiler in &["cc", "gcc", "clang", "musl-gcc"] {
        if let Ok(output) = std::process::Command::new("which")
            .arg(compiler)
            .output()
        {
            if output.status.success() {
                return Some(compiler.to_string());
            }
        }
        // Windows
        if let Ok(output) = std::process::Command::new("where")
            .arg(compiler)
            .output()
        {
            if output.status.success() {
                return Some(compiler.to_string());
            }
        }
    }
    None
}

fn binop_to_c(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::LtEq => "<=",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}
